# commented out all genres that are caught by rules
genre_aliases = [
    [' bpm',''],
#     ['140 bpm','140'],
#     ['160 bpm', '160'],
    ['1980s', '80s'],
    ['1990s', '90s'],
    ['a capella', 'a cappella'],
    ['acid tekno', 'acid techno'],
    # ['afro beats','afro beat'],
    ['alt county','alt country'],
    ['alternativehip hop', 'alternative hip hop'],
    ['avant gard', 'avant garde'],
    ['ambiant','ambient'],
    ['audio book','audiobooks'],
    # ['backing track', 'backing tracks'],
    # ['ballads', 'ballad'],
    # ['beat tapes', 'beat tape'],
    ['berlin school electronic music', 'berlin school'],
    ['break beat', 'breakbeat'],
    ['breakbeats', 'breakbeat'],
    # ['cassettes', 'cassette'],
    ['cassette tape', 'cassettes'],
    ['comedy songs', 'comedy'],
    ['chiptunes', 'chiptune'],
    ['chip tune', 'chiptune'],
    ['covers','cover'],
    ['dark techno industrial', 'dark techno,industrial'],
    ['dub step', 'dubstep'],
    ['tapes', 'tape'],
    ['christmas music', 'christmas'],
    ['dance hall', 'dancehall'],
    ['dance music', 'dance'],
    ['dark psy darkpsy', 'dark psy'],
    # ['demo', 'demos'],
    ['digeridoo','didgeridoo'],
    # ['disco edit', 'disco edits'],
    ['dnb', 'drum & bass'],
    ['down tempo', 'downtempo'],
    ['drone ambient', 'ambient drone'],
    # ['drum n bass', 'drum & bass'],
    ['drumandbass', 'drum & bass'],
    ['d&b', 'drum & bass'],
    ['dub step', 'dubstep'],
    ['dubstep & electronic','dubstep,electronic'],
    ['electronic dance music', 'edm'],
    ['eighties', '80s'],
    ['electronic body music', 'ebm'],
    ['eletronic', 'electronic'],
    ['electronic music', 'electronic'],
    ['electronica/dance','electronica,dance'],
    ['experiemental', 'experimental'],
    ['expiremental', 'experimental'],
    ['female vocalist', 'female vocals'],
    ['field recording', 'field recordings'],
    ['fingerstyle', 'fingerstyle guitar'],
    ['free download', 'free'],
    ['free tekno','techno'],
    ['free improv', 'free improvisation'],
    ['hard core', 'hardcore'],
    ['harmonies', 'harmony'],
    ['healing & meditation','healing,meditation'],
    ['heavy metal   hard rock', 'heavy metal,hard rock'],
    ['hiphop instrumental', 'hiphop instrumental'],
    ['hip hop instrumentals', 'hip hop instrumental'],
    ['hip hop rap', 'hip hop,rap'],
    ['hiphop rap', 'hip hop,rap'],
    ['hip hop/rap', 'hip hop,rap'],
    ['hip_hop', 'hip hop'],
    ['hip hop (real shit)', 'hip hop'],
    ['house techno minimal tech deep', 'house,techno,minimal,tech,deep'],
    ['indie pop rock','indie pop,indie rock'],
    ['indie rock pop','indie pop,indie rock'],
    ['instrumentalhip hop', 'instrumental hip hop'],
    ['jam track', 'jam'],
    ['jam tracks', 'jam'],
    ['jams', 'jam'],
    ['jazz & improvised music','jazz,improvised music'],
    ['left field', 'leftfield'],
    ['lgbt', 'lgbtq'],
    ['liquid dnb', 'liquid drum & bass'],
    ['live music', 'live'],
    ['live recording', 'live'],
    ['lo fi house', 'lo fihouse'],
    ['lofi hip hop', 'lo fi hip hop'],
    ['lofi hiphop', 'lo fi hip hop'],
    ['loop', 'loops'],
    ['love song', 'love songs'],
    ['mantras','mantra'],
    ['mash up', 'mash ups'],
    ['meditation music', 'meditation'],
    ['melancholic','melancholy'],
    ['metal core', 'metalcore'],
    ['montreal', 'montréal'],
    ['modular synth', 'modular synthesizer'],
    ['music for youtube', 'youtube'],
    ['nineties', '90s'],
    ['nostalgic', 'nostalgia'],
    ['oi','oi!'],
    ['podcasts', 'podcast'],
    ['post rock instrumental', 'post rock,instrumental'],
    ['psychadelic','psychedelic'],
    ['pyschedelic', 'psychedelic'],
    ['psyche','psych'],
    ['punk hardcore','hardcore punk'],
    ['r n b', 'r&b'],
    ['r & b', 'r&b'],
    ['rnb', 'r&b'],
    ['r&b/soul', 'r&b,soul'],
    ['rap & hip hop','rap,hip hop'],
    ['raga', 'ragga'],
    ['riot grrrl', 'riot grrl'],
    ['relaxation music', 'relaxation'],
    ['relaxing music', 'relaxing'],
    ['remixed','remix'],
    ['remixes', 'remix'],
    ['re edit', 're edits'],
    ['re issue', 'reissues'],
    ['rockandroll', 'rock & roll'],
    ['rock and roll', 'rock & roll'],
    ['rock n roll', 'rock & roll'],
    ['royalty free music', 'royalty free'],
    ['sample','samples'],
    ['sample based', 'sampling'],
    ['sci fi', 'science fiction'],
    ['scores','score'],
    ['scottish music', 'scottish'],
    ['shoegazing', 'shoegaze'],
    ['shoe gaze', 'shoegaze'],
    ['shoegazer','shoegaze'],
    ['soulfoul','soulful'],
    ['soundscape', 'soundscapes'],
    ['soundtracks', 'soundtrack'],
    ['soundtrack music', 'soundtrack'],
    ['spoken word poetry','spoken word'],
    ['steppas', 'steppa'],
    ['steppers', 'stepper'],
    ['synthwave 80s','synthwave,80s'],
    ['synthesizers', 'synthesizer'],
    ['technoandvariations', 'techno & variations'],
    ['tekno','techno'],
    ['techno hardcore','hardcore techno'],
    ['techno & variations', 'techno'],
    ['trap music', 'trap'],
    ['vgm', 'video game soundtrack'],
    ['videogame music', 'video game music'],
#     ['video game music', 'video game soundtrack'],
    ['world music', 'world'],
    ['yoga', 'yoga music']
]
